source 'https://rubygems.org'

ruby '~> 2.3.1'

# PostgreSQL driver
gem 'pg', '~> 0.18'

# Sinatra driver
gem 'sinatra', '~>1.4'
gem 'sinatra-contrib'

gem 'activerecord', '~> 5.0'
gem 'activesupport', '~> 5.0'

# Use Thin for our web server
gem 'thin'

gem 'rake', '~> 12.0.0'
gem 'shotgun'

gem 'pry'
gem 'rack', '1.6.8'
gem 'bcrypt'

# Adam's Gems
gem "irbtools"
gem 'will_paginate', '~> 3.1.0'
gem 'pry'

group :test do
  gem 'faker', '~> 1.7.3'
  gem 'rspec', '~> 3.5'
  gem 'rack-test'
  gem 'capybara'
end
