# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all' #=> Helps to load dependencies
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem "tux"
gem 'rack', '2.0.3'
gem 'rack-flash3'
gem 'sinatra-flash'

# PostgreSQL driver
gem 'pg'
# gem 'sqlite3'

## Adam's Gems ##
gem 'faker'
gem 'irbtools', require: 'irbtools/binding'
gem 'rspec', '~>3.0'
gem 'will_paginate', '~> 3.1.0'
