source 'https://rubygems.org'

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra', '~>1.4'
gem 'sinatra-contrib'

gem 'activesupport', '~>4.2.0'
gem 'activerecord', '~>4.2.0'
gem 'rake'
gem 'pry'
gem 'rack', '1.5.2'
gem 'shotgun'
gem 'faker'
gem 'bcrypt'
gem 'irbtools'

group :test do
  gem 'shoulda-matchers'
  gem 'rack-test'
  gem 'rspec', '~>3.0'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl'
end

# Adam's Gems
gem 'will_paginate', '~> 3.1.0'
